# Generated by Django 2.1.8 on 2019-06-28 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
