# Generated by Django 2.1.8 on 2019-07-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0003_sns_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
